config/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from invoice_board.api import urls as api_urls
from invoice_board.invoices.views import InvoicesBoardIndexView


urlpatterns = [
    url(r'^$', InvoicesBoardIndexView.as_view(), name='frontend-index'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    url(settings.ADMIN_URL, admin.site.urls),

    url(r'^users/', include('invoice_board.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^api/', include(api_urls, namespace='api-v1')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

invoice_board/api/urls.py
from django.urls import path

from invoice_board.api.invoices import endpoints
from invoice_board.api.settings.endpoints import AppGlobalsEndpoint

app_name = 'api-v1'

urlpatterns = [
    path('invoices/', endpoints.InvoiceListView.as_view(), name='invoice-list'),
    path('invoices/<int:pk>/', endpoints.InvoiceUpdateDeleteView.as_view(), name='invoice-update-delete'),

    path('globals/', AppGlobalsEndpoint.as_view())
]

invoice_board/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views


app_name = 'users'

urlpatterns = [
    url(r'^demo/$', views.DemoUserLoginView.as_view(), name='demo_login'),
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

invoice_board/client/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from soft_delete_it.models import SoftDeleteModel
# from softdelete import SoftDeleteObject
# Create your models here.

    
class SalesBroker(SoftDeleteModel):
    sales_broker_id = models.AutoField(primary_key = True, auto_created = True)
    first_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    middle_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    last_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    address_1 = models.CharField(max_length=100, default=None, blank=True, null=True)
    address_2 = models.CharField(max_length=100, default=None, blank=True, null=True)
    city  = models.CharField(max_length=100, default=None, blank=True, null=True)
    state = models.CharField(max_length=100, default=None, blank=True, null=True)
    country = models.CharField(max_length=100, default=None, blank=True, null=True)
    phone = models.CharField(max_length=100, default=None, blank=True, null=True)
    cell_phone = models.CharField(max_length=100, default=None, blank=True, null=True)
    email = models.EmailField()
    is_active = models.BooleanField(default = True)
    company_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    
    def __str__(self):
        return self.first_name + ' ' + self.last_name
    
    def get_absolute_url(self):
        return reverse('sales_broker_detail', kwargs={'id':self.sales_broker_id})
        
    

    


class TransactionFeeRateType(SoftDeleteModel):
    transaction_fee_rate_type_id = models.AutoField(auto_created=True, primary_key=True)
    transaction_fee_rate_type = models.CharField(max_length=50) #Flat, Daily, Bucket
    def __str__(self):
        return self.transaction_fee_rate_type
 
class Terms(SoftDeleteModel):
    terms_id = models.AutoField(auto_created=True, primary_key=True)
    description = models.CharField(max_length= 255, default=None, null=True, blank=True)
    advance_percentage = models.DecimalField(default=0, decimal_places=2, max_digits=4)
    security_percentage = models.DecimalField(default=0, decimal_places=2, max_digits=4)
    invoice_fee = models.DecimalField(default=0, decimal_places=2, max_digits=4)
    transaction_fee_rate_type = models.ForeignKey(TransactionFeeRateType, default=None, blank=True, null=True, on_delete=models.SET_NULL) # Foreign Key 
    flat_rate = models.DecimalField(default=0, decimal_places=4, max_digits=6)
    daily_rate = models.DecimalField(default=0,decimal_places=4, max_digits=6)
    express_processing_fee = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    priority_processing_fee = models.DecimalField(decimal_places=2, max_digits=4)
    standard_processing_fee = models.DecimalField(default=0, decimal_places=2, max_digits=4)
    fuel_advance_percentage = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    fuel_advance_fee_percentage = models.DecimalField(default=0, decimal_places=2, max_digits=4)
    fuel_advance_days = models.IntegerField(default=0)
    over_advance_fee_percentage = models.DecimalField(default=0, decimal_places=2, max_digits=4)
    over_advance_days = models.IntegerField(default=0)
    check_fee = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    wire_fee = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    transcheck_fee = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    ach_fee = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    fuel_card_fee = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    carrier_quck_pay_fee = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    paperwork_delivery_fee = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    postage_fee = models.DecimalField(default=0,decimal_places=2, max_digits=4)
    release_days = models.IntegerField(default=0)
    recourse_days = models.IntegerField(default=0)
    
    def get_absolute_url(self):
        return reverse('terms_detail', kwargs={'id':self.terms_id})


class BucketRate(SoftDeleteModel):
    bucket_rate_id = models.AutoField(auto_created=True, primary_key=True) 
    terms = models.ForeignKey(Terms, on_delete=models.CASCADE)  
    level = models.SmallIntegerField()
    min_days = models.SmallIntegerField()
    max_days = models.SmallIntegerField()
    percentage_rate = models.DecimalField(decimal_places=2, max_digits=4)
    
    def get_absolute_url(self):
        return reverse('bucket_rate_detail', kwargs={'id':self.bucket_rate_id})

class Client(SoftDeleteModel):
    client_id = models.AutoField(auto_created=True, primary_key=True)
    client_name = models.CharField(max_length=255)
    dba_name = models.CharField(max_length=255, default=None, blank=True, null=True)
    is_active = models.BooleanField(default = True)
    docket = models.CharField(max_length=50, default=None, blank=True, null=True)
    dot_number = models.CharField(max_length=50, default=None, blank=True, null=True)
    ein = models.CharField(max_length=50, default=None, blank=True, null=True)
    business_type = models.CharField(max_length=50, default=None, blank=True, null=True)
    is_broker = models.BooleanField(default = False)
    business_start_date = models.DateField(default=None, blank=True, null=True)
    funding_start_date = models.DateField(default=None, blank=True, null=True)
    fnding_end_date = models.DateField(default=None, blank=True, null=True)
    transaction_fee_rate_type = models.ForeignKey(TransactionFeeRateType, on_delete=models.PROTECT)
    business_phone = models.CharField(max_length=50, default=None, blank=True, null=True)
    business_fax = models.CharField(max_length=50, default=None, blank=True, null=True)
    business_email = models.EmailField(default=None, blank=True, null=True)
    number_of_trucks = models.IntegerField(default=None, blank=True, null=True)
    account_manager = models.ForeignKey(User, default=None, blank=True, null=True, on_delete = models.SET_NULL) # Foreign Key 
    primary_salesperson = models.ForeignKey(User, default=None, blank=True, null=True, on_delete = models.SET_NULL, related_name='salesperson_primary') # Foreign Key 
    secondary_salesperson = models.ForeignKey(User, default=None, blank=True, null=True, on_delete = models.SET_NULL, related_name='salesperson_secondary') # Foreign Key 
    sales_broker = models.ForeignKey(SalesBroker, default=None, blank=True, null=True, on_delete = models.SET_NULL) # Foreign Key 
    terms = models.ForeignKey(Terms, default=None, blank=True, null=True, on_delete = models.SET_NULL) # Foreign Key 
    hold_reserves = models.BooleanField(default = False)
    credit_limit = models.DecimalField(decimal_places =2, max_digits = 10)
    estimated_grp = models.DecimalField(decimal_places=2, max_digits = 4)
    estimated_volume = models.DecimalField(decimal_places =2, max_digits = 10)
    authority_status = models.BooleanField(default=True)
    insurance_status = models.BooleanField(default=True)
    insurance_expiration_date = models.DateField()
    ucc_filing_date = models.DateField()
    date_created = models.DateTimeField(auto_now_add=True)
    
    def get_absolute_url(self):
        return reverse('client_detail', kwargs={'id':self.client_id})

class ClientNote(SoftDeleteModel):
    client_note_id = models.AutoField(auto_created=True, primary_key=True),
    client = models.ForeignKey(Client, related_name='client_memo', on_delete = models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    client_note = models.CharField(max_length = 255)
    is_alert = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    show_processing = models.BooleanField(default=False)
    show_account_managers = models.BooleanField(default=False)
    show_collections = models.BooleanField(default=False)
    show_payments = models.BooleanField(default=False)
    show_client = models.BooleanField(default=False)
    
class ContactType(SoftDeleteModel):
    contact_type_id = models.AutoField(auto_created=True, primary_key=True)
    contact_type_name = models.CharField(max_length=50)
    contact_type_description = models.CharField(max_length=255)
    def __str__(self):
        return self.contact_type_name
    
class ContactAccount(SoftDeleteModel):
    contact_account_id = models.AutoField(auto_created=True, primary_key=True)
    date_created = models.DateTimeField(auto_now_add=True)
    first_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    middle_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    last_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    address_1 = models.CharField(max_length=100, default=None, blank=True, null=True)
    address_2 = models.CharField(max_length=100, default=None, blank=True, null=True)
    city  = models.CharField(max_length=100, default=None, blank=True, null=True)
    state = models.CharField(max_length=100, default=None, blank=True, null=True)
    country = models.CharField(max_length=100, default=None, blank=True, null=True)
    phone = models.CharField(max_length=100, default=None, blank=True, null=True)
    cell_phone = models.CharField(max_length=100, default=None, blank=True, null=True)
    email = models.EmailField(default=None, blank=True, null=True)
    is_active = models.BooleanField(default = True)
    contact_type = models.ForeignKey(ContactType,  default=None, blank=True, null=True, on_delete=models.SET_NULL)
    login = models.CharField(max_length=50, default=None, blank=True, null=True)
    password = models.CharField(max_length=50, default=None, blank=True, null=True)
    pin = models.CharField(max_length=50, default=None, blank=True, null=True)
    
    def get_absolute_url(self):

invoice_board/invoices/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from invoice_board.users.models import User


class InvoiceStatuses(object):
    NOT_PAID = 0
    PAID = 1

    @classmethod
    def as_choices(cls):
        return (
            (cls.NOT_PAID, "Pending"),
            (cls.PAID, "Paid")
        )


class InvoiceQuerySet(models.QuerySet):
    def NOT_PAID(self):
        return self.filter(status=InvoiceStatuses.NOT_PAID)


class Invoice(models.Model):
    name = models.CharField(_("Name"), max_length=80, blank=False)
    description = models.TextField(_("Description"), blank=False)
    status = models.SmallIntegerField(choices=InvoiceStatuses.as_choices(), default=InvoiceStatuses.NOT_PAID)
    modified_on = models.DateTimeField(auto_now=True)

    created_by = models.ForeignKey(User, related_name='invoices', null=False, on_delete=models.CASCADE)
    processed_by = models.ForeignKey(User, related_name='paid_invoices', null=True, on_delete=models.CASCADE)

    objects = InvoiceQuerySet.as_manager()

    class Meta:
        ordering = ['-modified_on']

    def __str__(self):
        return '%s' % (self.name)

    def save(self, *args, **kwargs):
        if self.status == InvoiceStatuses.NOT_PAID:
            self.processed_by = None

        super(Invoice, self).save(*args, **kwargs)

    def clean(self):
        # make sure processed_by field is set on setting of status to \'PAID\'
        if self.status == InvoiceStatuses.PAID and self.processed_by == None:
            raise ValidationError('processed_by field should be set on setting of status to \'PAID\'')

invoice_board/users/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    @property
    def fullname(self):
        return f'{self.first_name} {self.last_name}' if self.first_name or self.last_name else ''

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

invoice_board/invoices/forms.py
from django.forms import ModelForm

from crispy_forms.helper import FormHelper

from invoice_board.invoices.models import Invoice


class InvoiceForm(ModelForm):

    class Meta:
        model = Invoice
        fields = ['name', 'description', 'status']


    def __init__(self, *args, **kwargs):
        super(InvoiceForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False

invoice_board/client/views.py
from django.shortcuts import render
import requests
import logging

from urllib.parse import urlunparse, urlparse

from django import http
from django.conf import settings
from django.template import engines
from django.views.generic import TemplateView

from braces.views import LoginRequiredMixin


logger = logging.getLogger('general')


class ClientBoardIndexView(LoginRequiredMixin, TemplateView):
    """
    View that renders React App.
    """
    template_name = 'index.html'
    react_upstream = 'http://localhost:3000'
    cut_part = None

    def get(self, request, *args, **kwargs):
        if not settings.DEBUG:
            # just serve index.html because in production it has the reactjs scripts embedded.
            return super().get(request, *args, **kwargs)

        url = request.path
        upstream_url = self.react_upstream + url
        logger.debug(f'Proxying request to: {upstream_url}')

        response = requests.get(upstream_url, stream=True)
        content_type = response.headers.get('Content-Type')
        logger.debug(f'Response from {upstream_url}: {response}, {content_type}')

        if content_type == 'text/html; charset=UTF-8':
            context = self.get_context_data(**kwargs)
            return http.HttpResponse(
                content=engines['django'].from_string(response.text).render(context),
                status=response.status_code,
                reason=response.reason,
            )
        else:
            return http.StreamingHttpResponse(
                streaming_content=response.iter_content(2 ** 12),
                content_type=content_type,
                status=response.status_code,
                reason=response.reason,
            )

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['request'] = self.request
        return ctx

invoice_board/templates/invoices/invoice-modal-form.html
{% load static %} {% load crispy_forms_tags %}

<div class="modal fade" id="invoice-modal-form" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
          aria-hidden="true">&times;</span></button>
        <!--<h4 class="modal-title" id="myModalLabel">Invoice</h4>-->
      </div>
      <div class="modal-body">
        <div class="invoice-submit-status center-block"></div>
        <div class="invoice-form-wrapper">

        </div>
      </div>

      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<script type="text/html" id="invoice-editing-form-template">
  <form id="invoice-editing-form" class="center-block" action="" enctype="multipart/form-data" method="post">
    <div id="invoice-form-fields">
      {% csrf_token %}
      <div id="div_id_name" class="form-group"><label for="id_name" class="control-label  requiredField">
        Name<span class="asteriskField">*</span> </label>
        <div class="controls "><input class="textinput textInput form-control" id="id_name" maxlength="80" name="name"
          type="text" value="<%if (obj.name) {  %><%=name%><%  } %>" required/></div>
      </div>
      <hr>
      <div id="div_id_status" class="form-group"><label for="id_status" class="control-label  requiredField">
        Status<span class="asteriskField">*</span> </label>
        <div class="controls "><select class="select form-control" id="id_status" name="status" required>
          <option value="0" selected="selected">Not Paid</option>
          <option value="1">Paid</option>
        </select></div>
      </div>
      <hr>
      <div id="div_id_description" class="form-group"><label for="id_description" class="control-label  requiredField">
        Description<span class="asteriskField">*</span> </label>
        <div class="controls "> <textarea class="textarea form-control" cols="40"
          id="id_description" name="description" rows="10" required><%if (obj.description) {  %><%=description%><%  }%></textarea></div>
      </div>

    </div>

    <div class="form-group row">
      <div class="controls col-md-12">
        <%if (obj.name && obj.description) {  %>
        <button id="submit" class="btn btn-primary" type="submit"><i class="fa fa-pencil fa-fw" aria-hidden="true"></i> Apply</button>
        <% } else { %>
        <button id="submit" class="btn btn-primary" type="submit"><i class="fa fa-plus" aria-hidden="true"></i> Add</button>
        <% } %>
        <button id="cancel" class="btn btn-default" type="button">Cancel</button>
      </div>
    </div>
  </form>

</script>

<!-- processed_by : "None"
created_by_username : "alex"
description : "Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin"
id : 26
name : "Invoice number 15"
status : 0-->

<script type="text/html" id="invoice-information-template">
  <div class="row">
    <div id="invoice-name" class="col-md-7">
      <b>Name:</b>
      <%= name %>
    </div>
    <div class="col-md-5 text-right">
      <div class="control-buttons">
        <button id="edit-button" class="btn btn-default" title="Edit"><i class="fa fa-pencil" aria-hidden="true"></i></button>
        <button id="delete-button" class="btn btn-default" title="Delete"><i class="fa fa-trash" aria-hidden="true"></i></button>
        <button id="markdone-button" class="btn btn-default" title="Mark as Done"><i class="fa fa-check-circle-o" aria-hidden="true"></i></button>
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div id="invoice-general-info" class="col-md-12">
      <b>Created by:</b>
      <%= created_by_username %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <b>Status: </b> <span class="invoice-status"><%= status_readable %></span>
      <span class="invoice-accomplished-by">
      </span>
    </div>
  </div>
  <hr>
  <div class="row">
    <div id="invoice-description" class="col-md-12">
      <b>Description:</b>
      <%= description %>
    </div>
  </div>
</script>

<script type="text/html" id="server-error-template">
  <span class="server-status-label label label-danger">Server Internal Error</span>
  <h3>Ooops. Something went wrong.</h3>
  <p>Status
    <%= status %>
  </p>
  <p>
    <%= error %>
  </p>
  <button id="close-error-form" class="btn btn-primary col-md-6 col-md-offset-3" data-dismiss="modal">Ok</button>
</script>

<script type="text/html" id="invoice-short-info-question-template">
  <div class="row">
    <div id="invoice-name" class="col-md-7">
      <b>Name:</b>
      <%= name %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div id="invoice-general-info" class="col-md-12">
      <b>Created by:</b>
      <%= created_by_username %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <b>Status: </b> <span class="invoice-status label label-primary"><%= status_readable %></span>
    </div>
  </div>
  <hr>
  <div id="invoice-short-info-question-placeholder" class="center-block">
  </div>
</script>

<script type="text/html" id="invoice-delete-question-template">
  <h4>Are you sure you want to delete this invoice?</h4>
  <div class="control-buttons">
    <button id="confirm-button" class="btn btn-danger" type="submit"><i class="fa fa-trash fa-fw" aria-hidden="true"></i> Delete</button>
    <button id="cancel-button" class="btn btn-default">Cancel</button>
  </div>
</script>

<script type="text/html" id="invoice-delete-confirmation-template">
  <h4>Invoice deleted.</h4>
  <div class="control-buttons">
    <button id="close-form" class="btn btn-primary" data-dismiss="modal">Ok</button>
  </div>
</script>

<script type="text/html" id="invoice-markasdone-question-template">
  <h4>Mark this invoice as DONE?</h4>
  <div class="control-buttons">
    <button id="confirm-button" class="btn btn-success" type="submit"><i class="fa fa-check-circle-o fa-fw" aria-hidden="true"></i> Done</button>
    <button id="cancel-button" class="btn btn-default">Cancel</button>
  </div>
</script>

<script type="text/html" id="invoice-markasdone-confirmation-template">
  <h4>Invoice marked as DONE by you.</h4>
  <div class="control-buttons">
    <button id="close-form" class="btn btn-primary" data-dismiss="modal">OK</button>
  </div>
</script>

invoice_board/templates/invoices/invoice_api_list.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap_pagination %}

{% block css %}
{{ block.super }}
<link href="{% static 'css/invoice-list.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<span id="current-user-id" data-id="{{ user.pk }}"></span>

<div class="row invoice-list-page-header">
  <div class="col-md-1">
      <button id="add-button" class="btn btn-default" title="Add invoice" role="button" data-toggle="modal" data-target="#invoice-modal-form">
        <i class="fa fa-plus" aria-hidden="true"></i>
      </button>
  </div>
  <div class="col-md-7">
    {% if paginator %}
    {% bootstrap_paginate paginator.page range=10 %}
    {% endif %}
  </div>
  <div class="col-md-3">
    {% if invoicesdone_checkbox.is_shown %}
    <div class="checkbox" style="">
      <a href="{{ invoicesdone_checkbox.url }}">
        <label><input type="checkbox" value="" {{ invoicesdone_checkbox_is_checked }}
                      onclick='window.location.assign("{{ invoicesdone_checkbox.url }}")'>Don't show 'Done' invoices</label>
      </a>
    </div>
    {% endif %}
  </div>
  <div class="col-md-1">
    {% if filter_form %}
    <button style="float: right; " data-toggle="modal" data-target="#filtersModal"
            class="btn btn-default"> <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span>
      Search
    </button>
    {% endif %}
  </div>

</div>

<div class="row">
  <div class="col-md-12 invoice-list">
      <table class="table table-bordered">
        <tbody>
        <tr id="invoice-table-header" class="active">
          <th class="text-center">Name</th>
          <th class="text-center">Owner</th>
          <th class="text-center">Status</th>
          <th class="text-center">Actions</th>
        </tr>
        {% for invoice in results %}
          {% include 'invoices/invoice_table_row.html' %}
        {% endfor %}
        </tbody>
      </table>
  </div>
</div>

{% if filter_form %}
{{ filter_form }}
{% endif %}

{% include 'invoices/invoice-modal-form.html' %}

<script type="text/html" id="invoice-table-row-template">
  {% include 'invoices/invoice_table_row.html' %}
</script>

{% endblock content %}

{% block javascript %}
{{ block.super }}
<script src="{% static 'js/underscore-min.js' %}"></script>
<script src="{% static 'js/utils.js' %}"></script>
<script src="{% static 'js/invoice-forms.js' %}"></script>
<script src="{% static 'js/invoice-modal-controller.js' %}"></script>
{% endblock %}

invoice_board/templates/invoices/invoice_table_row.html
<tr class="invoice-list-item" id="invoice-id-{{ invoice.id }}" data-id="{{ invoice.id }}" data-name="{{ invoice.name }}"
      data-created_by="{{ invoice.created_by }}" data-created_by_username="{{ invoice.created_by_username }}"
      data-description="{{ invoice.description }}" data-processed_by="{{ invoice.processed_by }}" data-processed_by_username="{{ invoice.processed_by_username }}"
      data-status="{{ invoice.status }}" data-status_readable="{{ invoice.status_readable }}">
  <td class="col-md-6">
    <a class="invoice-link-dialog-toggler invoice-name" role="button" href="#invoice-information" data-toggle="modal"
              data-target="#invoice-modal-form">
      {{ invoice.name }}
    </a>
  </td>
  <td class="col-md-2 text-center invoice-created-by-username">
    {{ invoice.created_by_username }}
  </td>
  <td class="col-md-2 text-center">
    <span class="invoice-status">{{ invoice.status_readable }}</span>
    <span class="invoice-accomplished-by">
    </span>
  </td>
  <td class="col-md-2 text-center">
    <div class="control-buttons">
      <button id="edit-button" class="submit btn btn-default" style="display: none;" title="Edit" role="button" data-toggle="modal" data-target="#invoice-modal-form" disabled>
        <i class="fa fa-pencil" aria-hidden="true"></i>
      </button>
      <button id="delete-button" class="submit btn btn-default" style="display: none;" title="Delete" role="button" data-toggle="modal" data-target="#invoice-modal-form" disabled>
        <i class="fa fa-trash" aria-hidden="true"></i>
      </button>
      <button id="markdone-button" class="submit btn btn-default" title="Mark as Done" role="button" data-toggle="modal" data-target="#invoice-modal-form" disabled>
        <i class="fa fa-check-circle-o" aria-hidden="true"></i>
      </button> 
    </div>
  </td>
</tr>